/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: DR PRESIDENT (https://sketchfab.com/drpresident)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lotus3-b93b3c95eadc4ad1afab3013d2331904
Title: Lotus3
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Lotus(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/lotus/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="35f0f424f54f45ccbdb13f4f98fd6f86fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Stamen">
                  <group name="Stamen_0" position={[5.91, 13.3, 1.64]} rotation={[-1.4, 0.92, 1.35]} scale={0.83}>
                    <mesh name="Stamen_0__0" geometry={nodes.Stamen_0__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_1" position={[5.51, 13.3, 3.14]} rotation={[-1.1, 0.83, 0.97]} scale={0.83}>
                    <mesh name="Stamen_1__0" geometry={nodes.Stamen_1__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_2" position={[4.73, 13.3, 4.49]} rotation={[-0.89, 0.69, 0.66]} scale={0.83}>
                    <mesh name="Stamen_2__0" geometry={nodes.Stamen_2__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_3" position={[3.63, 13.3, 5.59]} rotation={[-0.76, 0.51, 0.43]} scale={0.83}>
                    <mesh name="Stamen_3__0" geometry={nodes.Stamen_3__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_4" position={[2.28, 13.3, 6.37]} rotation={[-0.68, 0.31, 0.24]} scale={0.83}>
                    <mesh name="Stamen_4__0" geometry={nodes.Stamen_4__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_5" position={[0.78, 13.3, 6.77]} rotation={[-0.65, 0.1, 0.08]} scale={0.83}>
                    <mesh name="Stamen_5__0" geometry={nodes.Stamen_5__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_6" position={[-0.78, 13.3, 6.77]} rotation={[-0.65, -0.1, -0.08]} scale={0.83}>
                    <mesh name="Stamen_6__0" geometry={nodes.Stamen_6__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_7" position={[-2.28, 13.3, 6.37]} rotation={[-0.68, -0.31, -0.24]} scale={0.83}>
                    <mesh name="Stamen_7__0" geometry={nodes.Stamen_7__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_8" position={[-3.63, 13.3, 5.59]} rotation={[-0.76, -0.51, -0.43]} scale={0.83}>
                    <mesh name="Stamen_8__0" geometry={nodes.Stamen_8__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_9" position={[-4.73, 13.3, 4.49]} rotation={[-0.89, -0.69, -0.66]} scale={0.83}>
                    <mesh name="Stamen_9__0" geometry={nodes.Stamen_9__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_10" position={[-5.51, 13.3, 3.14]} rotation={[-1.1, -0.83, -0.97]} scale={0.83}>
                    <mesh name="Stamen_10__0" geometry={nodes.Stamen_10__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_11" position={[-5.91, 13.3, 1.64]} rotation={[-1.4, -0.92, -1.35]} scale={0.83}>
                    <mesh name="Stamen_11__0" geometry={nodes.Stamen_11__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_12" position={[-5.91, 13.3, 0.08]} rotation={[-1.74, -0.92, -1.79]} scale={0.83}>
                    <mesh name="Stamen_12__0" geometry={nodes.Stamen_12__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_13" position={[-5.51, 13.3, -1.42]} rotation={[-2.04, -0.83, -2.18]} scale={0.83}>
                    <mesh name="Stamen_13__0" geometry={nodes.Stamen_13__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_14" position={[-4.73, 13.3, -2.77]} rotation={[-2.25, -0.69, -2.48]} scale={0.83}>
                    <mesh name="Stamen_14__0" geometry={nodes.Stamen_14__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_15" position={[-3.63, 13.3, -3.87]} rotation={[-2.38, -0.51, -2.71]} scale={0.83}>
                    <mesh name="Stamen_15__0" geometry={nodes.Stamen_15__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_16" position={[-2.28, 13.3, -4.65]} rotation={[-2.46, -0.31, -2.9]} scale={0.83}>
                    <mesh name="Stamen_16__0" geometry={nodes.Stamen_16__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_17" position={[-0.78, 13.3, -5.05]} rotation={[-2.49, -0.1, -3.06]} scale={0.83}>
                    <mesh name="Stamen_17__0" geometry={nodes.Stamen_17__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_18" position={[0.78, 13.3, -5.05]} rotation={[-2.49, 0.1, 3.06]} scale={0.83}>
                    <mesh name="Stamen_18__0" geometry={nodes.Stamen_18__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_19" position={[2.28, 13.3, -4.65]} rotation={[-2.46, 0.31, 2.9]} scale={0.83}>
                    <mesh name="Stamen_19__0" geometry={nodes.Stamen_19__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_20" position={[3.63, 13.3, -3.87]} rotation={[-2.38, 0.51, 2.71]} scale={0.83}>
                    <mesh name="Stamen_20__0" geometry={nodes.Stamen_20__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_21" position={[4.73, 13.3, -2.77]} rotation={[-2.25, 0.69, 2.48]} scale={0.83}>
                    <mesh name="Stamen_21__0" geometry={nodes.Stamen_21__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_22" position={[5.51, 13.3, -1.42]} rotation={[-2.04, 0.83, 2.18]} scale={0.83}>
                    <mesh name="Stamen_22__0" geometry={nodes.Stamen_22__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_23" position={[5.91, 13.3, 0.08]} rotation={[-1.74, 0.92, 1.79]} scale={0.83}>
                    <mesh name="Stamen_23__0" geometry={nodes.Stamen_23__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_24" position={[14.29, 16.74, 2.58]} rotation={[-1.73, 1.05, 1.68]} scale={0.88}>
                    <mesh name="Stamen_24__0" geometry={nodes.Stamen_24__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_25" position={[13.36, 16.74, 6.22]} rotation={[-1.26, 1.05, 1.15]} scale={0.89}>
                    <mesh name="Stamen_25__0" geometry={nodes.Stamen_25__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_26" position={[11.51, 16.74, 9.49]} rotation={[-0.89, 0.93, 0.71]} scale={0.9}>
                    <mesh name="Stamen_26__0" geometry={nodes.Stamen_26__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_27" position={[8.89, 16.74, 12.18]} rotation={[-0.66, 0.75, 0.42]} scale={0.91}>
                    <mesh name="Stamen_27__0" geometry={nodes.Stamen_27__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_28" position={[5.66, 16.74, 14.09]} rotation={[-0.53, 0.54, 0.23]} scale={0.92}>
                    <mesh name="Stamen_28__0" geometry={nodes.Stamen_28__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_29" position={[2.04, 16.74, 15.1]} rotation={[-0.46, 0.31, 0.09]} scale={0.93}>
                    <mesh name="Stamen_29__0" geometry={nodes.Stamen_29__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_30" position={[-1.72, 16.74, 15.15]} rotation={[-0.44, 0.08, -0.03]} scale={0.93}>
                    <mesh name="Stamen_30__0" geometry={nodes.Stamen_30__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_31" position={[-5.36, 16.74, 14.22]} rotation={[-0.45, -0.16, -0.14]} scale={0.92}>
                    <mesh name="Stamen_31__0" geometry={nodes.Stamen_31__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_32" position={[-8.63, 16.74, 12.38]} rotation={[-0.5, -0.39, -0.27]} scale={0.91}>
                    <mesh name="Stamen_32__0" geometry={nodes.Stamen_32__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_33" position={[-11.32, 16.74, 9.75]} rotation={[-0.59, -0.61, -0.43]} scale={0.9}>
                    <mesh name="Stamen_33__0" geometry={nodes.Stamen_33__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_34" position={[-13.23, 16.74, 6.52]} rotation={[-0.76, -0.8, -0.66]} scale={0.89}>
                    <mesh name="Stamen_34__0" geometry={nodes.Stamen_34__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_35" position={[-14.24, 16.74, 2.9]} rotation={[-1.02, -0.96, -0.99]} scale={0.88}>
                    <mesh name="Stamen_35__0" geometry={nodes.Stamen_35__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_36" position={[-14.29, 16.74, -0.86]} rotation={[-1.42, -1.05, -1.46]} scale={0.88}>
                    <mesh name="Stamen_36__0" geometry={nodes.Stamen_36__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_37" position={[-13.36, 16.74, -4.5]} rotation={[-1.86, -1.03, -1.98]} scale={0.88}>
                    <mesh name="Stamen_37__0" geometry={nodes.Stamen_37__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_38" position={[-11.51, 16.74, -7.77]} rotation={[-2.22, -0.91, -2.4]} scale={0.88}>
                    <mesh name="Stamen_38__0" geometry={nodes.Stamen_38__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_39" position={[-8.89, 16.74, -10.46]} rotation={[-2.44, -0.74, -2.69]} scale={0.89}>
                    <mesh name="Stamen_39__0" geometry={nodes.Stamen_39__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_40" position={[-5.66, 16.74, -12.37]} rotation={[-2.56, -0.53, -2.89]} scale={0.89}>
                    <mesh name="Stamen_40__0" geometry={nodes.Stamen_40__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_41" position={[-2.04, 16.74, -13.38]} rotation={[-2.63, -0.31, -3.04]} scale={0.9}>
                    <mesh name="Stamen_41__0" geometry={nodes.Stamen_41__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_42" position={[1.72, 16.74, -13.43]} rotation={[-2.66, -0.08, 3.12]} scale={0.9}>
                    <mesh name="Stamen_42__0" geometry={nodes.Stamen_42__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_43" position={[5.36, 16.74, -12.5]} rotation={[-2.65, 0.15, 2.99]} scale={0.9}>
                    <mesh name="Stamen_43__0" geometry={nodes.Stamen_43__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_44" position={[8.63, 16.74, -10.65]} rotation={[-2.6, 0.38, 2.86]} scale={0.89}>
                    <mesh name="Stamen_44__0" geometry={nodes.Stamen_44__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_45" position={[11.32, 16.74, -8.03]} rotation={[-2.51, 0.6, 2.69]} scale={0.88}>
                    <mesh name="Stamen_45__0" geometry={nodes.Stamen_45__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_46" position={[13.23, 16.74, -4.8]} rotation={[-2.36, 0.79, 2.46]} scale={0.88}>
                    <mesh name="Stamen_46__0" geometry={nodes.Stamen_46__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_47" position={[14.24, 16.74, -1.18]} rotation={[-2.11, 0.95, 2.14]} scale={0.88}>
                    <mesh name="Stamen_47__0" geometry={nodes.Stamen_47__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_48" position={[12.25, 15.92, 2.47]} rotation={[-1.41, 0.89, 1.36]} scale={0.85}>
                    <mesh name="Stamen_48__0" geometry={nodes.Stamen_48__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_49" position={[11.42, 15.92, 5.59]} rotation={[-1.11, 0.82, 0.98]} scale={0.86}>
                    <mesh name="Stamen_49__0" geometry={nodes.Stamen_49__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_50" position={[9.8, 15.92, 8.38]} rotation={[-0.89, 0.69, 0.66]} scale={0.87}>
                    <mesh name="Stamen_50__0" geometry={nodes.Stamen_50__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_51" position={[7.52, 15.92, 10.66]} rotation={[-0.74, 0.52, 0.42]} scale={0.88}>
                    <mesh name="Stamen_51__0" geometry={nodes.Stamen_51__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_52" position={[4.73, 15.92, 12.28]} rotation={[-0.65, 0.32, 0.23]} scale={0.89}>
                    <mesh name="Stamen_52__0" geometry={nodes.Stamen_52__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_53" position={[1.61, 15.92, 13.11]} rotation={[-0.61, 0.11, 0.07]} scale={0.89}>
                    <mesh name="Stamen_53__0" geometry={nodes.Stamen_53__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_54" position={[-1.61, 15.92, 13.11]} rotation={[-0.61, -0.11, -0.07]} scale={0.89}>
                    <mesh name="Stamen_54__0" geometry={nodes.Stamen_54__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_55" position={[-4.73, 15.92, 12.28]} rotation={[-0.65, -0.32, -0.23]} scale={0.89}>
                    <mesh name="Stamen_55__0" geometry={nodes.Stamen_55__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_56" position={[-7.52, 15.92, 10.66]} rotation={[-0.74, -0.52, -0.42]} scale={0.88}>
                    <mesh name="Stamen_56__0" geometry={nodes.Stamen_56__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_57" position={[-9.8, 15.92, 8.38]} rotation={[-0.89, -0.69, -0.66]} scale={0.87}>
                    <mesh name="Stamen_57__0" geometry={nodes.Stamen_57__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_58" position={[-11.42, 15.92, 5.59]} rotation={[-1.11, -0.82, -0.98]} scale={0.86}>
                    <mesh name="Stamen_58__0" geometry={nodes.Stamen_58__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_59" position={[-12.25, 15.92, 2.47]} rotation={[-1.41, -0.89, -1.36]} scale={0.85}>
                    <mesh name="Stamen_59__0" geometry={nodes.Stamen_59__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_60" position={[-12.25, 15.92, -0.75]} rotation={[-1.73, -0.88, -1.78]} scale={0.85}>
                    <mesh name="Stamen_60__0" geometry={nodes.Stamen_60__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_61" position={[-11.42, 15.92, -3.87]} rotation={[-2.01, -0.8, -2.15]} scale={0.85}>
                    <mesh name="Stamen_61__0" geometry={nodes.Stamen_61__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_62" position={[-9.8, 15.92, -6.66]} rotation={[-2.22, -0.67, -2.46]} scale={0.85}>
                    <mesh name="Stamen_62__0" geometry={nodes.Stamen_62__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_63" position={[-7.52, 15.92, -8.94]} rotation={[-2.36, -0.5, -2.7]} scale={0.85}>
                    <mesh name="Stamen_63__0" geometry={nodes.Stamen_63__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_64" position={[-4.73, 15.92, -10.56]} rotation={[-2.44, -0.31, -2.89]} scale={0.86}>
                    <mesh name="Stamen_64__0" geometry={nodes.Stamen_64__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_65" position={[-1.61, 15.92, -11.39]} rotation={[-2.48, -0.1, -3.06]} scale={0.86}>
                    <mesh name="Stamen_65__0" geometry={nodes.Stamen_65__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_66" position={[1.61, 15.92, -11.39]} rotation={[-2.48, 0.1, 3.06]} scale={0.86}>
                    <mesh name="Stamen_66__0" geometry={nodes.Stamen_66__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_67" position={[4.73, 15.92, -10.56]} rotation={[-2.44, 0.31, 2.89]} scale={0.86}>
                    <mesh name="Stamen_67__0" geometry={nodes.Stamen_67__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_68" position={[7.52, 15.92, -8.94]} rotation={[-2.36, 0.5, 2.7]} scale={0.85}>
                    <mesh name="Stamen_68__0" geometry={nodes.Stamen_68__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_69" position={[9.8, 15.92, -6.66]} rotation={[-2.22, 0.67, 2.46]} scale={0.85}>
                    <mesh name="Stamen_69__0" geometry={nodes.Stamen_69__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_70" position={[11.42, 15.92, -3.87]} rotation={[-2.01, 0.8, 2.15]} scale={0.85}>
                    <mesh name="Stamen_70__0" geometry={nodes.Stamen_70__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_71" position={[12.25, 15.92, -0.75]} rotation={[-1.73, 0.88, 1.78]} scale={0.85}>
                    <mesh name="Stamen_71__0" geometry={nodes.Stamen_71__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_72" position={[9.4, 14.69, 2.1]} rotation={[-1.41, 0.89, 1.36]} scale={0.83}>
                    <mesh name="Stamen_72__0" geometry={nodes.Stamen_72__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_73" position={[8.76, 14.69, 4.49]} rotation={[-1.12, 0.81, 0.98]} scale={0.83}>
                    <mesh name="Stamen_73__0" geometry={nodes.Stamen_73__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_74" position={[7.52, 14.69, 6.63]} rotation={[-0.91, 0.67, 0.68]} scale={0.83}>
                    <mesh name="Stamen_74__0" geometry={nodes.Stamen_74__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_75" position={[5.77, 14.69, 8.38]} rotation={[-0.78, 0.5, 0.44]} scale={0.83}>
                    <mesh name="Stamen_75__0" geometry={nodes.Stamen_75__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_76" position={[3.63, 14.69, 9.62]} rotation={[-0.69, 0.31, 0.25]} scale={0.84}>
                    <mesh name="Stamen_76__0" geometry={nodes.Stamen_76__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_77" position={[1.24, 14.69, 10.26]} rotation={[-0.65, 0.1, 0.08]} scale={0.84}>
                    <mesh name="Stamen_77__0" geometry={nodes.Stamen_77__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_78" position={[-1.24, 14.69, 10.26]} rotation={[-0.65, -0.1, -0.08]} scale={0.84}>
                    <mesh name="Stamen_78__0" geometry={nodes.Stamen_78__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_79" position={[-3.63, 14.69, 9.62]} rotation={[-0.69, -0.31, -0.25]} scale={0.84}>
                    <mesh name="Stamen_79__0" geometry={nodes.Stamen_79__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_80" position={[-5.77, 14.69, 8.38]} rotation={[-0.78, -0.5, -0.44]} scale={0.83}>
                    <mesh name="Stamen_80__0" geometry={nodes.Stamen_80__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_81" position={[-7.52, 14.69, 6.63]} rotation={[-0.91, -0.67, -0.68]} scale={0.83}>
                    <mesh name="Stamen_81__0" geometry={nodes.Stamen_81__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_82" position={[-8.76, 14.69, 4.49]} rotation={[-1.12, -0.81, -0.98]} scale={0.83}>
                    <mesh name="Stamen_82__0" geometry={nodes.Stamen_82__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_83" position={[-9.4, 14.69, 2.1]} rotation={[-1.41, -0.89, -1.36]} scale={0.83}>
                    <mesh name="Stamen_83__0" geometry={nodes.Stamen_83__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_84" position={[-9.4, 14.69, -0.38]} rotation={[-1.73, -0.89, -1.78]} scale={0.83}>
                    <mesh name="Stamen_84__0" geometry={nodes.Stamen_84__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_85" position={[-8.76, 14.69, -2.77]} rotation={[-2.02, -0.81, -2.16]} scale={0.83}>
                    <mesh name="Stamen_85__0" geometry={nodes.Stamen_85__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_86" position={[-7.52, 14.69, -4.91]} rotation={[-2.23, -0.67, -2.46]} scale={0.83}>
                    <mesh name="Stamen_86__0" geometry={nodes.Stamen_86__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_87" position={[-5.77, 14.69, -6.66]} rotation={[-2.36, -0.5, -2.7]} scale={0.83}>
                    <mesh name="Stamen_87__0" geometry={nodes.Stamen_87__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_88" position={[-3.63, 14.69, -7.9]} rotation={[-2.43, -0.31, -2.89]} scale={0.83}>
                    <mesh name="Stamen_88__0" geometry={nodes.Stamen_88__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_89" position={[-1.24, 14.69, -8.54]} rotation={[-2.47, -0.1, -3.06]} scale={0.83}>
                    <mesh name="Stamen_89__0" geometry={nodes.Stamen_89__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_90" position={[1.24, 14.69, -8.54]} rotation={[-2.47, 0.1, 3.06]} scale={0.83}>
                    <mesh name="Stamen_90__0" geometry={nodes.Stamen_90__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_91" position={[3.63, 14.69, -7.9]} rotation={[-2.43, 0.31, 2.89]} scale={0.83}>
                    <mesh name="Stamen_91__0" geometry={nodes.Stamen_91__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_92" position={[5.77, 14.69, -6.66]} rotation={[-2.36, 0.5, 2.7]} scale={0.83}>
                    <mesh name="Stamen_92__0" geometry={nodes.Stamen_92__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_93" position={[7.52, 14.69, -4.91]} rotation={[-2.23, 0.67, 2.46]} scale={0.83}>
                    <mesh name="Stamen_93__0" geometry={nodes.Stamen_93__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_94" position={[8.76, 14.69, -2.77]} rotation={[-2.02, 0.81, 2.16]} scale={0.83}>
                    <mesh name="Stamen_94__0" geometry={nodes.Stamen_94__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                  <group name="Stamen_95" position={[9.4, 14.69, -0.38]} rotation={[-1.73, 0.89, 1.78]} scale={0.83}>
                    <mesh name="Stamen_95__0" geometry={nodes.Stamen_95__0.geometry} material={materials['Scene_-_Root']} />
                  </group>
                </group>
                <group name="Reference_Geo" position={[0, 22.26, 0.86]} rotation={[-Math.PI, 0, 0]}>
                  <mesh name="Reference_Geo__0" geometry={nodes.Reference_Geo__0.geometry} material={materials['Scene_-_Root']} />
                </group>
                <group name="Lotus_Animate">
                  <group name="Cloner_1" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0" position={[0, 0, -7]} rotation={[-0.89, -0.01, -0.28]} scale={0.55}>
                      <group name="New_Petal_0_2">
                        <mesh name="New_Petal_0_2__0" geometry={nodes.New_Petal_0_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1" position={[4.95, 0, -4.95]} rotation={[-1.06, -0.47, -0.94]} scale={0.55}>
                      <group name="New_Petal_1_2">
                        <mesh name="New_Petal_1_2__0" geometry={nodes.New_Petal_1_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2" position={[7, 0, 0]} rotation={[-1.58, -0.68, -1.86]} scale={0.55}>
                      <group name="New_Petal_2_2">
                        <mesh name="New_Petal_2_2__0" geometry={nodes.New_Petal_2_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3" position={[4.95, 0, 4.95]} rotation={[-2.1, -0.45, -2.76]} scale={0.55}>
                      <group name="New_Petal_3_2">
                        <mesh name="New_Petal_3_2__0" geometry={nodes.New_Petal_3_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4" position={[0, 0, 7]} rotation={[-2.25, 0.01, 2.87]} scale={0.55}>
                      <group name="New_Petal_4_2">
                        <mesh name="New_Petal_4_2__0" geometry={nodes.New_Petal_4_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5" position={[-4.95, 0, 4.95]} rotation={[-2.09, 0.47, 2.2]} scale={0.55}>
                      <group name="New_Petal_5_2">
                        <mesh name="New_Petal_5_2__0" geometry={nodes.New_Petal_5_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6" position={[-7, 0, 0]} rotation={[-1.56, 0.68, 1.29]} scale={0.55}>
                      <group name="New_Petal_6_2">
                        <mesh name="New_Petal_6_2__0" geometry={nodes.New_Petal_6_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7" position={[-4.95, 0, -4.95]} rotation={[-1.04, 0.45, 0.38]} scale={0.55}>
                      <group name="New_Petal_7_2">
                        <mesh name="New_Petal_7_2__0" geometry={nodes.New_Petal_7_2__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_2" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_3" position={[0, 0, -7]} rotation={[-0.27, -0.02, -0.27]} scale={0.79}>
                      <group name="New_Petal_0_4">
                        <mesh name="New_Petal_0_4__0" geometry={nodes.New_Petal_0_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_3" position={[4.95, 0, -4.95]} rotation={[-0.37, -0.77, -0.53]} scale={0.79}>
                      <group name="New_Petal_1_4">
                        <mesh name="New_Petal_1_4__0" geometry={nodes.New_Petal_1_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_3" position={[7, 0, 0]} rotation={[-1.63, -1.3, -1.9]} scale={0.79}>
                      <group name="New_Petal_2_4">
                        <mesh name="New_Petal_2_4__0" geometry={nodes.New_Petal_2_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_3" position={[4.95, 0, 4.95]} rotation={[-2.78, -0.73, 3.13]} scale={0.79}>
                      <group name="New_Petal_3_4">
                        <mesh name="New_Petal_3_4__0" geometry={nodes.New_Petal_3_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_3" position={[0, 0, 7]} rotation={[-2.88, 0.02, 2.88]} scale={0.79}>
                      <group name="New_Petal_4_4">
                        <mesh name="New_Petal_4_4__0" geometry={nodes.New_Petal_4_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_3" position={[-4.95, 0, 4.95]} rotation={[-2.77, 0.77, 2.61]} scale={0.79}>
                      <group name="New_Petal_5_4">
                        <mesh name="New_Petal_5_4__0" geometry={nodes.New_Petal_5_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_3" position={[-7, 0, 0]} rotation={[-1.51, 1.3, 1.24]} scale={0.79}>
                      <group name="New_Petal_6_4">
                        <mesh name="New_Petal_6_4__0" geometry={nodes.New_Petal_6_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_3" position={[-4.95, 0, -4.95]} rotation={[-0.36, 0.73, -0.01]} scale={0.79}>
                      <group name="New_Petal_7_4">
                        <mesh name="New_Petal_7_4__0" geometry={nodes.New_Petal_7_4__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_3" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_5" position={[0, 0, -7]} rotation={[0.5, -0.02, -0.25]} scale={0.98}>
                      <group name="New_Petal_0_6">
                        <mesh name="New_Petal_0_6__0" geometry={nodes.New_Petal_0_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_5" position={[4.95, 0, -4.95]} rotation={[0.66, -0.69, 0.2]} scale={0.98}>
                      <group name="New_Petal_1_6">
                        <mesh name="New_Petal_1_6__0" geometry={nodes.New_Petal_1_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_5" position={[7, 0, 0]} rotation={[1.6, -1.08, 1.35]} scale={0.98}>
                      <group name="New_Petal_2_6">
                        <mesh name="New_Petal_2_6__0" geometry={nodes.New_Petal_2_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_5" position={[4.95, 0, 4.95]} rotation={[2.5, -0.66, 2.45]} scale={0.98}>
                      <group name="New_Petal_3_6">
                        <mesh name="New_Petal_3_6__0" geometry={nodes.New_Petal_3_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_5" position={[0, 0, 7]} rotation={[2.65, 0.02, 2.89]} scale={0.98}>
                      <group name="New_Petal_4_6">
                        <mesh name="New_Petal_4_6__0" geometry={nodes.New_Petal_4_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_5" position={[-4.95, 0, 4.95]} rotation={[2.48, 0.69, -2.95]} scale={0.98}>
                      <group name="New_Petal_5_6">
                        <mesh name="New_Petal_5_6__0" geometry={nodes.New_Petal_5_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_5" position={[-7, 0, 0]} rotation={[1.54, 1.08, -1.8]} scale={0.98}>
                      <group name="New_Petal_6_6">
                        <mesh name="New_Petal_6_6__0" geometry={nodes.New_Petal_6_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_5" position={[-4.95, 0, -4.95]} rotation={[0.64, 0.66, -0.69]} scale={0.98}>
                      <group name="New_Petal_7_6">
                        <mesh name="New_Petal_7_6__0" geometry={nodes.New_Petal_7_6__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_4" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_7" position={[0, 0, -7]} rotation={[1.22, -0.01, -0.25]} scale={0.23}>
                      <group name="New_Petal_0_8">
                        <mesh name="New_Petal_0_8__0" geometry={nodes.New_Petal_0_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_7" position={[4.95, 0, -4.95]} rotation={[1.32, -0.25, 0.51]} scale={0.23}>
                      <group name="New_Petal_1_8">
                        <mesh name="New_Petal_1_8__0" geometry={nodes.New_Petal_1_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_7" position={[7, 0, 0]} rotation={[1.58, -0.35, 1.33]} scale={0.23}>
                      <group name="New_Petal_2_8">
                        <mesh name="New_Petal_2_8__0" geometry={nodes.New_Petal_2_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_7" position={[4.95, 0, 4.95]} rotation={[1.83, -0.24, 2.14]} scale={0.23}>
                      <group name="New_Petal_3_8">
                        <mesh name="New_Petal_3_8__0" geometry={nodes.New_Petal_3_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_7" position={[0, 0, 7]} rotation={[1.92, 0.01, 2.9]} scale={0.23}>
                      <group name="New_Petal_4_8">
                        <mesh name="New_Petal_4_8__0" geometry={nodes.New_Petal_4_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_7" position={[-4.95, 0, 4.95]} rotation={[1.82, 0.25, -2.63]} scale={0.23}>
                      <group name="New_Petal_5_8">
                        <mesh name="New_Petal_5_8__0" geometry={nodes.New_Petal_5_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_7" position={[-7, 0, 0]} rotation={[1.56, 0.35, -1.81]} scale={0.23}>
                      <group name="New_Petal_6_8">
                        <mesh name="New_Petal_6_8__0" geometry={nodes.New_Petal_6_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_7" position={[-4.95, 0, -4.95]} rotation={[1.31, 0.24, -1]} scale={0.23}>
                      <group name="New_Petal_7_8">
                        <mesh name="New_Petal_7_8__0" geometry={nodes.New_Petal_7_8__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_5" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_9" position={[0, 0, -7]} rotation={[2.09, 0.01, -0.25]} scale={0.1}>
                      <group name="New_Petal_0_10">
                        <mesh name="New_Petal_0_10__0" geometry={nodes.New_Petal_0_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_9" position={[4.95, 0, -4.95]} rotation={[1.95, 0.37, 0.47]} scale={0.1}>
                      <group name="New_Petal_1_10">
                        <mesh name="New_Petal_1_10__0" geometry={nodes.New_Petal_1_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_9" position={[7, 0, 0]} rotation={[1.56, 0.52, 1.33]} scale={0.1}>
                      <group name="New_Petal_2_10">
                        <mesh name="New_Petal_2_10__0" geometry={nodes.New_Petal_2_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_9" position={[4.95, 0, 4.95]} rotation={[1.18, 0.35, 2.18]} scale={0.1}>
                      <group name="New_Petal_3_10">
                        <mesh name="New_Petal_3_10__0" geometry={nodes.New_Petal_3_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_9" position={[0, 0, 7]} rotation={[1.05, -0.01, 2.89]} scale={0.1}>
                      <group name="New_Petal_4_10">
                        <mesh name="New_Petal_4_10__0" geometry={nodes.New_Petal_4_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_9" position={[-4.95, 0, 4.95]} rotation={[1.19, -0.37, -2.67]} scale={0.1}>
                      <group name="New_Petal_5_10">
                        <mesh name="New_Petal_5_10__0" geometry={nodes.New_Petal_5_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_9" position={[-7, 0, 0]} rotation={[1.58, -0.52, -1.81]} scale={0.1}>
                      <group name="New_Petal_6_10">
                        <mesh name="New_Petal_6_10__0" geometry={nodes.New_Petal_6_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_9" position={[-4.95, 0, -4.95]} rotation={[1.96, -0.35, -0.96]} scale={0.1}>
                      <group name="New_Petal_7_10">
                        <mesh name="New_Petal_7_10__0" geometry={nodes.New_Petal_7_10__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_6" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_11" position={[0, 0, -7]} rotation={[2.09, 0.01, -0.25]} scale={0.1}>
                      <group name="New_Petal_0_12">
                        <mesh name="New_Petal_0_12__0" geometry={nodes.New_Petal_0_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_11" position={[4.95, 0, -4.95]} rotation={[1.95, 0.37, 0.47]} scale={0.1}>
                      <group name="New_Petal_1_12">
                        <mesh name="New_Petal_1_12__0" geometry={nodes.New_Petal_1_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_11" position={[7, 0, 0]} rotation={[1.56, 0.52, 1.33]} scale={0.1}>
                      <group name="New_Petal_2_12">
                        <mesh name="New_Petal_2_12__0" geometry={nodes.New_Petal_2_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_11" position={[4.95, 0, 4.95]} rotation={[1.18, 0.35, 2.18]} scale={0.1}>
                      <group name="New_Petal_3_12">
                        <mesh name="New_Petal_3_12__0" geometry={nodes.New_Petal_3_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_11" position={[0, 0, 7]} rotation={[1.05, -0.01, 2.89]} scale={0.1}>
                      <group name="New_Petal_4_12">
                        <mesh name="New_Petal_4_12__0" geometry={nodes.New_Petal_4_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_11" position={[-4.95, 0, 4.95]} rotation={[1.19, -0.37, -2.67]} scale={0.1}>
                      <group name="New_Petal_5_12">
                        <mesh name="New_Petal_5_12__0" geometry={nodes.New_Petal_5_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_11" position={[-7, 0, 0]} rotation={[1.58, -0.52, -1.81]} scale={0.1}>
                      <group name="New_Petal_6_12">
                        <mesh name="New_Petal_6_12__0" geometry={nodes.New_Petal_6_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_11" position={[-4.95, 0, -4.95]} rotation={[1.96, -0.35, -0.96]} scale={0.1}>
                      <group name="New_Petal_7_12">
                        <mesh name="New_Petal_7_12__0" geometry={nodes.New_Petal_7_12__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_7" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_13" position={[0, 0, -7]} rotation={[2.76, 0.02, -0.26]} scale={0.1}>
                      <group name="New_Petal_0_14">
                        <mesh name="New_Petal_0_14__0" geometry={nodes.New_Petal_0_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_13" position={[4.95, 0, -4.95]} rotation={[2.62, 0.73, 0.11]} scale={0.1}>
                      <group name="New_Petal_1_14">
                        <mesh name="New_Petal_1_14__0" geometry={nodes.New_Petal_1_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_13" position={[7, 0, 0]} rotation={[1.53, 1.19, 1.36]} scale={0.1}>
                      <group name="New_Petal_2_14">
                        <mesh name="New_Petal_2_14__0" geometry={nodes.New_Petal_2_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_13" position={[4.95, 0, 4.95]} rotation={[0.51, 0.7, 2.54]} scale={0.1}>
                      <group name="New_Petal_3_14">
                        <mesh name="New_Petal_3_14__0" geometry={nodes.New_Petal_3_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_13" position={[0, 0, 7]} rotation={[0.38, -0.02, 2.89]} scale={0.1}>
                      <group name="New_Petal_4_14">
                        <mesh name="New_Petal_4_14__0" geometry={nodes.New_Petal_4_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_13" position={[-4.95, 0, 4.95]} rotation={[0.52, -0.73, -3.04]} scale={0.1}>
                      <group name="New_Petal_5_14">
                        <mesh name="New_Petal_5_14__0" geometry={nodes.New_Petal_5_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_13" position={[-7, 0, 0]} rotation={[1.61, -1.19, -1.79]} scale={0.1}>
                      <group name="New_Petal_6_14">
                        <mesh name="New_Petal_6_14__0" geometry={nodes.New_Petal_6_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_13" position={[-4.95, 0, -4.95]} rotation={[2.63, -0.7, -0.61]} scale={0.1}>
                      <group name="New_Petal_7_14">
                        <mesh name="New_Petal_7_14__0" geometry={nodes.New_Petal_7_14__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_8" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_15" position={[0, 0, -7]} rotation={[-2.85, 0.02, -0.27]} scale={0.1}>
                      <group name="New_Petal_0_16">
                        <mesh name="New_Petal_0_16__0" geometry={nodes.New_Petal_0_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_15" position={[4.95, 0, -4.95]} rotation={[-2.73, 0.76, -0.55]} scale={0.1}>
                      <group name="New_Petal_1_16">
                        <mesh name="New_Petal_1_16__0" geometry={nodes.New_Petal_1_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_15" position={[7, 0, 0]} rotation={[-1.51, 1.28, -1.89]} scale={0.1}>
                      <group name="New_Petal_2_16">
                        <mesh name="New_Petal_2_16__0" geometry={nodes.New_Petal_2_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_15" position={[4.95, 0, 4.95]} rotation={[-0.4, 0.73, -3.13]} scale={0.1}>
                      <group name="New_Petal_3_16">
                        <mesh name="New_Petal_3_16__0" geometry={nodes.New_Petal_3_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_15" position={[0, 0, 7]} rotation={[-0.29, -0.02, 2.87]} scale={0.1}>
                      <group name="New_Petal_4_16">
                        <mesh name="New_Petal_4_16__0" geometry={nodes.New_Petal_4_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_15" position={[-4.95, 0, 4.95]} rotation={[-0.41, -0.76, 2.59]} scale={0.1}>
                      <group name="New_Petal_5_16">
                        <mesh name="New_Petal_5_16__0" geometry={nodes.New_Petal_5_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_15" position={[-7, 0, 0]} rotation={[-1.63, -1.28, 1.25]} scale={0.1}>
                      <group name="New_Petal_6_16">
                        <mesh name="New_Petal_6_16__0" geometry={nodes.New_Petal_6_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_15" position={[-4.95, 0, -4.95]} rotation={[-2.74, -0.73, 0.01]} scale={0.1}>
                      <group name="New_Petal_7_16">
                        <mesh name="New_Petal_7_16__0" geometry={nodes.New_Petal_7_16__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_9" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_17" position={[0, 0, -7]} rotation={[-2.38, 0.01, -0.27]} scale={0.1}>
                      <group name="New_Petal_0_18">
                        <mesh name="New_Petal_0_18__0" geometry={nodes.New_Petal_0_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_17" position={[4.95, 0, -4.95]} rotation={[-2.2, 0.55, -0.88]} scale={0.1}>
                      <group name="New_Petal_1_18">
                        <mesh name="New_Petal_1_18__0" geometry={nodes.New_Petal_1_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_17" position={[7, 0, 0]} rotation={[-1.55, 0.81, -1.86]} scale={0.1}>
                      <group name="New_Petal_2_18">
                        <mesh name="New_Petal_2_18__0" geometry={nodes.New_Petal_2_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_17" position={[4.95, 0, 4.95]} rotation={[-0.93, 0.53, -2.81]} scale={0.1}>
                      <group name="New_Petal_3_18">
                        <mesh name="New_Petal_3_18__0" geometry={nodes.New_Petal_3_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_17" position={[0, 0, 7]} rotation={[-0.76, -0.01, 2.87]} scale={0.1}>
                      <group name="New_Petal_4_18">
                        <mesh name="New_Petal_4_18__0" geometry={nodes.New_Petal_4_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_17" position={[-4.95, 0, 4.95]} rotation={[-0.94, -0.55, 2.26]} scale={0.1}>
                      <group name="New_Petal_5_18">
                        <mesh name="New_Petal_5_18__0" geometry={nodes.New_Petal_5_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_17" position={[-7, 0, 0]} rotation={[-1.59, -0.81, 1.28]} scale={0.1}>
                      <group name="New_Petal_6_18">
                        <mesh name="New_Petal_6_18__0" geometry={nodes.New_Petal_6_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_17" position={[-4.95, 0, -4.95]} rotation={[-2.21, -0.53, 0.33]} scale={0.1}>
                      <group name="New_Petal_7_18">
                        <mesh name="New_Petal_7_18__0" geometry={nodes.New_Petal_7_18__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                  <group name="Cloner_10" position={[0, 10.02, 0]} rotation={[0, -Math.PI / 9, 0]}>
                    <group name="New_Petal_0_19" position={[0, 0, -7]} rotation={[-2.04, 0.01, -0.28]} scale={0.1}>
                      <group name="New_Petal_0_20">
                        <mesh name="New_Petal_0_20__0" geometry={nodes.New_Petal_0_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_1_19" position={[4.95, 0, -4.95]} rotation={[-1.91, 0.33, -1.01]} scale={0.1}>
                      <group name="New_Petal_1_20">
                        <mesh name="New_Petal_1_20__0" geometry={nodes.New_Petal_1_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_2_19" position={[7, 0, 0]} rotation={[-1.56, 0.47, -1.85]} scale={0.1}>
                      <group name="New_Petal_2_20">
                        <mesh name="New_Petal_2_20__0" geometry={nodes.New_Petal_2_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_3_19" position={[4.95, 0, 4.95]} rotation={[-1.22, 0.32, -2.69]} scale={0.1}>
                      <group name="New_Petal_3_20">
                        <mesh name="New_Petal_3_20__0" geometry={nodes.New_Petal_3_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_4_19" position={[0, 0, 7]} rotation={[-1.1, -0.01, 2.86]} scale={0.1}>
                      <group name="New_Petal_4_20">
                        <mesh name="New_Petal_4_20__0" geometry={nodes.New_Petal_4_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_5_19" position={[-4.95, 0, 4.95]} rotation={[-1.23, -0.33, 2.13]} scale={0.1}>
                      <group name="New_Petal_5_20">
                        <mesh name="New_Petal_5_20__0" geometry={nodes.New_Petal_5_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_6_19" position={[-7, 0, 0]} rotation={[-1.58, -0.47, 1.29]} scale={0.1}>
                      <group name="New_Petal_6_20">
                        <mesh name="New_Petal_6_20__0" geometry={nodes.New_Petal_6_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                    <group name="New_Petal_7_19" position={[-4.95, 0, -4.95]} rotation={[-1.92, -0.32, 0.45]} scale={0.1}>
                      <group name="New_Petal_7_20">
                        <mesh name="New_Petal_7_20__0" geometry={nodes.New_Petal_7_20__0.geometry} material={materials['Scene_-_Root']} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/lotus/scene-transformed.glb')
